### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by charlie199** [BePsvPT/Facebook-Anonymous-Publisher#8]
I am a newbie.
I tried to build this app on OpenShift . 
Here is my steps:
1. Click Create your first application now 
2. In the application type list, find Laravel 5.0 and select it.
3. Copy an paste the following URL to the Source Code field

> https://github.com/BePsvPT/Facebook-Anonymous-Publisher/

After finishing, it showed HTTP ERROR 500
Is there any mistakes? Thanks

**Comment by BePsvPT** [comment]
This project is using laravel 5.2 and php 7.0.

According to [laravel document](https://laravel.com/docs/5.0#server-requirements), the php requirement of laravel 5.0 is >= 5.4 and < 7. I think this is the reason that result in http 500 error.

**Comment by charlie199** [comment]
Thx for your reply.

But which platform would you choose?
Heroku? Fortrabbit?

Sorry, I don't understand how to choose.

**Comment by BePsvPT** [comment]
DigitalOcean is the platform i'm using.

This is a great for developing and low flow website because the pricing is cheaper than others.

If your website flow is large, AWS or Google Compute Engine is more suitable because of its scalability.

**Comment by charlie199** [comment]
Thx

**Comment by charlie199** [comment]
Sorry, I just found that the php version on OpenShift is 5.4
Is there other reasons for Http 500 error?
